services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=encurtador'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: